-- =====================================================
-- Supabase Seed: RC Peptides Affiliate Products
-- Generated from Peptides-Product-Sheets.csv
-- All URLs include ref=PEPTIDESDECODED
-- =====================================================

INSERT INTO affiliate_products (id, product_name, category, slug, price, promotion_status, evidence_level, rc_product_url, scientific_summary, what_we_know, what_we_dont_know, what_changes, protocol, warning, cta_text)
VALUES
  ('bpc-157-5mg', 'BPC-157 5mg', 'Recovery tissulaire', 'bpc-157-5mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/bpc-157-5mg?ref=PEPTIDESDECODED', 'Méta-analyse 19 RCTs / 1 341 participants', '- Réduction 23% temps guérison (p<0.01) - Effet dose-dépendant (0.5-2 mg/kg) - Upregulation VEGF + angiogenèse accélérée', '- Demi-vie courte (~4h) = injection BID requise - Pas données long terme (>6 mois) - 60% études financées fabricants', '- Protocole optimal : 1 mg SC BID 4-6 semaines - COA batch-visible obligatoire (pureté >99%) - Éviter si antécédents cancer (théorie angiogenèse)', '1 mg SC BID 4-6 semaines', 'Antécédents cancer / grossesse', 'Voir COA + prix →')
  ,('tirzepatide-10mg', 'Tirzepatide 10mg', 'GLP-1/GIP', 'tirzepatide-10mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/tirzepatide-10mg?ref=PEPTIDESDECODED', 'SURMOUNT-1 n=2 539', '- -22.5% poids vs -14.9% (sémaglutide) - Double agoniste GLP-1 + GIP = synergique - GI side effects similaires (nausea 20-25%)', '- Effets long terme (>2 ans) non documentés - Tapering protocol : pas consensus - Interactions médicamenteuses : peu données', '- First-line : Tirzepatide si BMI >35 Sinon si BMI 30-35 - Titration : 2.5mg → 5mg → 10mg (4 semaines) - Monitoring : TSH lipase creatinine Q3M', '2.5mg → 5mg → 10mg (4 semaines) 10mg maintenance', 'Diabète type 1 / pancréatite / grossesse', 'Voir COA + prix →')
  ,('tb-500-5mg', 'TB-500 5mg', 'Recovery musculaire', 'tb-500-5mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/tb-500-5mg?ref=PEPTIDESDECODED', 'Thymosin Beta-4 fragment', '- Accélération régénération myocytes - Anti-inflammatoire systémique - Synergie BPC-157 documentée', '- Pas RCTs humains (que modèles animaux) - Clearance rénale : ajuster si insuffisance - Demi-vie ~7-10 jours', '- Protocole : 2.5-5 mg SC 2x/semaine 4-8 semaines - Combo BPC-157 + TB-500 = effet synergique - Injection SC (pas IM requis)', '2.5-5 mg SC 2x/semaine 4-8 semaines', 'Cancer actif (théorie métastases) / grossesse', 'Voir COA + prix →')
  ,('cjc-1295-ipamorelin-2mg', 'CJC-1295 + Ipamorelin 2mg', 'GH secretagogue', 'cjc-1295-ipamorelin-2mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/cjc-1295-ipamorelin-2mg?ref=PEPTIDESDECODED', 'DAC + GHRP combo', '- Augmentation GH pulsatile (pic ~30 min post-injection) - IGF-1 élévation sustained (4-6h) - Moins side effects vs GHRP-6', '- Tachyphylaxie après 8-12 semaines (break requis) - Pas données long terme (>6 mois cycles) - Interactions insuline/glucose', '- Protocole : 1 mg SC pre-sleep ou pre-workout - Cycle : 8 semaines ON / 4 semaines OFF - Monitoring : IGF-1 Q8W', '1 mg SC pre-sleep 8 semaines ON / 4 OFF', 'Cancer actif / diabète insulino-dépendant', 'Voir COA + prix →')
  ,('semax-10mg', 'Semax 10mg', 'Nootrope cognitive', 'semax-10mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/semax-10mg?ref=PEPTIDESDECODED', 'ACTH(4-10) analog', '- Amélioration mémoire working (RCTs Russie n=120) - Neuroprotection ischémie (modèles animaux) - BDNF élévation', '- Pas RCTs occidentaux (que Russie/Ukraine) - Demi-vie courte (~2h) = dosing TID - Stabilité température : données limitées', '- Protocole : 10 mg IN/SQ matin + midi (pas soir = insomnia) - Cycle : 4-6 semaines - Stockage : 4C', '10 mg IN matin + midi 4-6 semaines', 'Anxiété sévère / bipolarité', 'Voir COA + prix →')
  ,('ghk-cu-50mg', 'GHK-Cu 50mg', 'Cosmétique / Hair', 'ghk-cu-50mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/ghk-cu-50mg?ref=PEPTIDESDECODED', 'Copper peptide', '- Stimule collagen I/III (RCTs 12 semaines) - Réduction perte cheveux (androgenic alopecia) - Cicatrisation accélérée', '- Purity critique (>99% requis) - Stabilité oxydation : packaging airless requis - Effet dose-dépendant (10-50 mg optimal)', '- Protocole : 20-50 mg SC 3x/semaine OU topical 1-2% daily - Combo : Minoxidil + GHK = synergique - Stockage : 4C', '20-50 mg SC 3x/semaine ou topical 1-2% daily', 'Allergie cuivre / Wilson disease', 'Voir COA + prix →')
  ,('fisetin-500mg', 'Fisetin 500mg', 'Senolytic', 'fisetin-500mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/fisetin-500mg?ref=PEPTIDESDECODED', 'Flavonoïde', '- Sénolytique (élimination senescent cells) - Extension lifespan modèles murins (10-15%) - Anti-inflammatoire NLRP3', '- Biodisponibilité faible (liposomal requis) - Pas RCTs long terme humains - Dosing optimal : encore débattu', '- Protocole : 20 mg/kg J1-J2 puis 1x/mois (Mayo Clinic) - Liposomal : 500 mg BID J1-J2 - Combo : Quercetin + Dasatinib (si résistance)', '500 mg BID J1-J2 puis 1x/mois', 'Grossesse / insuffisance rénale', 'Voir COA + prix →')
  ,('aod-9604-5mg', 'AOD-9604 5mg', 'Fat loss', 'aod-9604-5mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/aod-9604-5mg?ref=PEPTIDESDECODED', 'GH fragment 177-191', '- Lipolyse sélective (adipocytes blancs) - Pas effet sur glucose/IGF-1 (vs GH full) - Synergie CJC-1295', '- Efficacité modeste sans deficit calorique - 50% répondeurs (génétique dépendante) - Pas données >12 semaines', '- Protocole : 2.5-5 mg SC matin fasted + cardio - Combo : CJC-1295 + AOD = synergique - Durée : 8-12 semaines', '2.5-5 mg SC matin fasted 8-12 semaines', 'Cancer actif / grossesse', 'Voir COA + prix →')
  ,('thymosin-alpha-1-10mg', 'Thymosin Alpha-1 10mg', 'Immune modulation', 'thymosin-alpha-1-10mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/thymosin-alpha-1-10mg?ref=PEPTIDESDECODED', 'Polypeptide thymique', '- Activation T-cells CD4+/CD8+ - Adjuvant vaccins (hépatite B influenza) - Réduction viral load (hépatite C chronic)', '- Pas RCTs larges (que petites cohorte) - Injection frequency critique (BID optimal) - Coût élevé vs alternatives', '- Protocole : 2.5 mg SC 2x/semaine 4-12 semaines - Post-vaccination : boost T-cell response - Combo : KPV = synergique', '2.5 mg SC 2x/semaine 4-12 semaines', 'Transplant (rejet risk) / autoimmune disease', 'Voir COA + prix →')
  ,('kpv-5mg', 'KPV 5mg', 'Immune / Anti-inflammatoire', 'kpv-5mg', NULL, 'EDITORIAL_REVIEW', 'VARYING', 'https://rcpeptides.to/products/kpv-5mg?ref=PEPTIDESDECODED', 'Pro-opiomelanocortin fragment', '- Anti-inflammatoire puissant (α-MSH analog) - Protection barrière intestinale (IBD modèles) - Synergie BPC-157 + Thymosin', '- Pas RCTs humains (que préclinique) - Demi-vie ultra-courte (~30 min) - Stabilité pH : données limitées', '- Protocole : 2.5-5 mg SC 2-3x/semaine - Combo : BPC-157 + KPV = gut repair - Stockage : 4C', '2.5-5 mg SC 2-3x/semaine', 'Grossesse / allaitement', 'Voir COA + prix →')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================
-- End of seed data
-- =====================================================
